// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
	"github.com/realHoangHai/kratos/api/gen/go/conf"
	"github.com/realHoangHai/kratos/app/core/internal/data"
	"github.com/realHoangHai/kratos/app/core/internal/server"
	"github.com/realHoangHai/kratos/app/core/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(logger log.Logger, registrar registry.Registrar, bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	client := data.NewEntClient(bootstrap, logger)
	redisClient := data.NewRedisClient(bootstrap, logger)
	dataData, cleanup, err := data.NewData(client, redisClient, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userService := service.NewUserService(logger, userRepo)
	roleRepo := data.NewRoleRepo(dataData, logger)
	roleService := service.NewRoleService(logger, roleRepo)
	permissionRepo := data.NewPermissionRepo(dataData, logger)
	permissionService := service.NewPermissionService(logger, permissionRepo)
	grpcServer := server.NewGRPCServer(bootstrap, logger, userService, roleService, permissionService)
	app := newApp(logger, registrar, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
