# transport
server:
  http:
    addr: "0.0.0.0:9800"
    timeout: 10s
    enable_swagger: true
    cors:
      headers:
        - "X-Requested-With"
        - "Content-Type"
        - "Authorization"
      methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "HEAD"
        - "OPTIONS"
      origins:
        - "*"
    middleware:
      auth:
        method: "HS256"
        key: "some_api_key"

  grpc:
    addr: "0.0.0.0:0"
    timeout: 10s
    middleware:

client:
  grpc:
    timeout: 10s
    middleware:
      enable_logging: true
      enable_recovery: true
      enable_tracing: true
      enable_validate: true
      enable_circuit_breaker: true
      auth:
        method: ""
        key: "some_api_key"

# ----------------------------------------------------------------------------------------------------------------------
# data
data:
  redis:
    addr: "localhost:6379"
    dial_timeout: 10s
    read_timeout: 0.4s
    write_timeout: 0.6s

# ----------------------------------------------------------------------------------------------------------------------
# logger
logger:
  type: std

  zap:
    level: "debug"
    filename: "./logs/info.log"
    max_size: 1
    max_age: 30
    max_backups: 5

# ----------------------------------------------------------------------------------------------------------------------
# tracing
trace:
  enable: false

# ----------------------------------------------------------------------------------------------------------------------
# remote


# ----------------------------------------------------------------------------------------------------------------------
# registry
